# Generated by Django 6.0.1 on 2026-01-27 23:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_historialsalida'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='preferred_provider',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.proveedor'),
        ),
    ]
