# Generated by Django 6.0.1 on 2026-01-28 17:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_userprofile_preferred_provider'),
    ]

    operations = [
        migrations.CreateModel(
            name='HistorialCompra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.IntegerField()),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('llave', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='compras', to='api.llaves')),
                ('proveedor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='compras_historial', to='api.proveedor')),
            ],
        ),
    ]
