# Generated by Django 6.0.1 on 2026-01-28 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_historialcompra'),
    ]

    operations = [
        migrations.AddField(
            model_name='historialcompra',
            name='precio_pago',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
