# Generated by Django 6.0.1 on 2026-01-28 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_historialcompra_precio_pago'),
    ]

    operations = [
        migrations.AddField(
            model_name='llaves',
            name='precio_compra',
            field=models.DecimalField(decimal_places=2, default=0.9, max_digits=10),
        ),
    ]
