# Generated by Django 6.0.1 on 2026-01-28 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_llaves_precio_compra'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='llaves',
            constraint=models.UniqueConstraint(fields=('cod_llave', 'proveedor'), name='unique_llave_per_proveedor'),
        ),
    ]
