# Generated by Django 6.0.1 on 2026-01-28 21:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_llaves_unique_llave_per_proveedor'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='active_provider_color',
            field=models.CharField(default='indigo', max_length=20),
        ),
    ]
